# Generated by Django 4.2.29 on 2026-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culinary',
            name='image',
        ),
        migrations.AddField(
            model_name='culinary',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
