# Generated by Django 4.2.29 on 2026-06-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_culinary_image_culinary_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelagency',
            name='is_active',
        ),
        migrations.AddField(
            model_name='travelagency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
